---
# tasks file for configure_firewall
- name: lastest security packages verson installed
  yum:
    name: "{{ security_packages }}"
    state: latest
- name: firewall enabled and running
  service:
    name: "{{ item }}"
    enable: true
    state: started
  with_items: "{{ services_to_enable }}"
- name: Configure firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: ture
  with_items: "{{ firewall_services }}"

